/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#2c4e36",
        "secondary-container": "#e2e0d7",
        "surface-container-low": "#f3f4ef",
        "tertiary-fixed-dim": "#a9d0b0",
        "on-surface": "#1a1c19",
        "on-secondary": "#ffffff",
        background: "#f9faf5",
        "surface-container": "#edeee9",
        "surface-container-lowest": "#ffffff",
        tertiary: "#3a5d44",
        "error-container": "#ffdad6",
        "on-primary-container": "#cbfed4",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#c9c6be",
        "surface-variant": "#e2e3de",
        "on-error-container": "#93000a",
        secondary: "#5f5f58",
        "secondary-fixed": "#e5e2da",
        "on-tertiary-container": "#d3fbda",
        outline: "#717971",
        "surface-container-high": "#e7e9e4",
        "on-tertiary-fixed": "#00210e",
        "on-primary-fixed": "#00210d",
        "surface-container-highest": "#e2e3de",
        "on-primary": "#ffffff",
        primary: "#325f3f",
        "tertiary-fixed": "#c5eccb",
        "on-secondary-fixed": "#1c1c17",
        surface: "#f9faf5",
        "on-secondary-fixed-variant": "#474741",
        "outline-variant": "#c1c9bf",
        "surface-dim": "#d9dad6",
        "primary-container": "#4a7856",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#bcefc5",
        "surface-tint": "#3a6847",
        "inverse-on-surface": "#f0f1ec",
        "tertiary-container": "#52765b",
        "inverse-primary": "#a1d2aa",
        "on-background": "#1a1c19",
        "inverse-surface": "#2e312e",
        "on-error": "#ffffff",
        "on-secondary-container": "#64635c",
        "primary-fixed-dim": "#a1d2aa",
        "on-surface-variant": "#414941",
        "surface-bright": "#f9faf5",
        "on-primary-fixed-variant": "#225031",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "container-max": "1280px",
        xl: "40px",
        sm: "8px",
        gutter: "24px",
        md: "16px",
        xs: "4px",
        lg: "24px",
      },
      fontFamily: {
        sans: ["Poppins", "Inter", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        h1: ["Poppins", "sans-serif"],
        h2: ["Poppins", "sans-serif"],
        h3: ["Poppins", "sans-serif"],
        "body-lg": ["Poppins", "sans-serif"],
        "body-md": ["Poppins", "sans-serif"],
        "body-sm": ["Poppins", "sans-serif"],
        "label-caps": ["Poppins", "sans-serif"],
        button: ["Poppins", "sans-serif"],
      },
      fontSize: {
        h2: [
          "32px",
          {
            lineHeight: "1.25",
            fontWeight: "600",
          },
        ],
        h1: [
          "40px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "1.6",
            fontWeight: "400",
          },
        ],
        h3: [
          "24px",
          {
            lineHeight: "1.3",
            fontWeight: "500",
          },
        ],
        "label-caps": [
          "12px",
          {
            lineHeight: "1",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        button: [
          "15px",
          {
            lineHeight: "1",
            fontWeight: "500",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "1.5",
            fontWeight: "400",
          },
        ],
        "body-sm": [
          "14px",
          {
            lineHeight: "1.5",
            fontWeight: "400",
          },
        ],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
